apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: day303-api
  namespace: day303
spec:
  rules:
    - host: day303.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: day303-api
                port:
                  number: 80
